### ISSUE TITLE
How to get token in flutter web ? 

### ISSUE THREAD

**Issue by bakboem** [CoderSpinoza/kakao_flutter_sdk#9]
return code only ..

**Comment by CoderSpinoza** [comment]
You can pass the authorization code to AuthApi class. Below is a sample code.

```dart
void loginButtonClicked() async {
  try {
    String authCode = await AuthCodeClient.instance.request();
    AccessToken token = await AuthApi.instance.issueAccessToken(authCode);
    AccessTokenStore.instance.toCache(token);
  } catch (e) {
    // some error happened during the course of user login... deal with it.
  }
}
```

**Comment by bakboem** [comment]
okey..  i'll try 

web also needs to added  <KakaoContext.clientId> ?

this is error info.
error on issuing access token: {error: misconfigured, error_description: invalid android_key_hash or ios_bundle_id or web_site_url}
--------------------------------

**Comment by CoderSpinoza** [comment]
Oh, sorry did not realize you are working on flutter web. As of 0.3.2, this SDK does not support Flutter web yet. There are two problems.

1. SDK itself will not be able to get authorization code because it currently lacks platform-specific code for getting authorization code.
1. Kakao API server did not allow CORS and any request in the browser will be blocked.

The first issue could be addressed with the next release (https://github.com/CoderSpinoza/kakao_flutter_sdk/commit/8cd4f29b0c078e9744e8c9a8beaf07248eef7856 contains the relevant code) but the second issue should be addressed by Kakao API team itself. Therefore, it might take a little longer.

What you can do for now is get token with the next release (0.4.0) and pass that token to server and call on the server side. If you need this feature, then I will hurry with the next release.

**Comment by bakboem** [comment]
thank you !~
I will wait patiently for the next update ^^ 
good luck, man!

**Comment by CoderSpinoza** [comment]
Haha I will update you when it's done. I would appreciate it if you could star this repo :)

**Comment by bakboem** [comment]
I'm sorry for the late reply..
this is good library !~  thank you!

**Comment by bakboem** [comment]
Hi Kang~
How are you doing? 
I'm waiting for you to update  hah

**Comment by CoderSpinoza** [comment]
> 2. Kakao API server did not allow CORS and any request in the browser will be blocked.

Number 2 from above list is still not addressed. I am sorry for the delay.

I have created a separate issue #10  for web support so you can f/u there. I will close this issue.

Thanks for your interest in Kakao API and Kakao Flutter SDK.
